name: Deploy
on: [push, workflow_dispatch]
# jobs for steps
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: get code
        uses: actions/checkout@v4.2.2
      - name: install node jobs
        uses: actions/setup-node@v3.9.1
        with: 
          node-version: '20'

      - name: print node node-version
        run: node -v
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
